#
# Run macros
#

install-rust: &install-rust
  run:
    name: Install Rust
    command: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable

restore-artifacts-from-workspace: &restore-artifacts-from-workspace
  attach_workspace:
    at: target/artifacts

#
# Main document
#

version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: ping crates.io
      - *install-rust
      - run: PATH="$USERPROFILE\.cargo\bin:$PATH" cargo build --no-default-features
