[transforms.javascript]
title = "JavaScript"
allow_you_to_description = "transform events with a full embedded JavaScript engine"
beta = true
common = true
function_category = "program"
guides = []
input_types = ["log"]
output_types = ["log"]
resources = [
  {name = "ES 2019 Specification", short_link = "es2019_spec"}
]

[transforms.javascript.options.source]
type = "string"
examples = [
"""\
event => ({...event, field: 'value'})
"""
]
common = true
null = true
description = "The inline JavaScript source with handler function."

[transforms.javascript.options.path]
type = "string"
examples = ["/etc/vector/transform.js"]
null = true
description = "The path to JavaScript source file with handler function."

[transforms.javascript.options.handler]
type = "string"
examples = ["handler"]
common = true
null = true
description = "Name of the handler function."

[transforms.javascript.options.memory_limit]
type = "int"
examples = [10000000]
null = true
description = "Maximum allowed RAM usage for JavaScript engine in bytes."
